name: Rosie Mendoza Photography
favicon: null
layout_spectrum: 0.25365
typography_spectrum: 0.99896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22131b'
    - '#b38b9a'
    - '#7e6265'
    - '#d6d5f1'
    - '#7da837'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
