name: Rosie Mendoza Photography
favicon: null
layout_spectrum: 0.25365
typography_spectrum: 0.50209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#589bd8'
    - '#000000'
    - '#ebf0f3'
    - '#0a3855'
    - '#787065'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
