name: Rosie Mendoza Photography
favicon: null
layout_spectrum: 0.25365
typography_spectrum: 0.74843
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#70929e'
    - '#008276'
    - '#498b8d'
    - '#277a79'
    - '#a3b6c7'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
