name: Rosie Mendoza Photography
favicon: null
layout_spectrum: 0.5021198212634772
typography_spectrum: 0.5338259523268789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#475a5f'
    - '#ff8e69'
    - '#081016'
    - '#00a4af'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
